name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run docker-compose
        uses: sudo-bot/action-docker-compose@latest
        with:
          cli-args: -f docker-compose.ci.yaml up -d

      - name: Chown in /var/www
        run: docker exec -u root -t app chown -R www-data:www-data /var/www

      - name: Copy .env
        run: docker exec -t app cp .env.example .env

      - name: Copy .env.testing
        run: docker exec -t app cp .env.testing.example .env.testing

      - name: Install composer dependencies
        run: docker exec -t app composer install

      - name: Run Laravel key:generate
        run: docker exec -t app php /var/www/artisan key:generate

      - name: Run migrations
        run: docker exec -t app php /var/www/artisan migrate

      - name: Run PHPUnit
        run: docker exec -t app php /var/www/vendor/bin/phpunit -c /var/www/phpunit.xml
